apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4i-operators
spec:
  generators:
  - list:
      elements:
        - name: openshift-cert-manager
          namespace: cert-manager-operator
        - name: platformnavigator
          namespace: cp4i2
        - name: apiconnect
          namespace: cp4i2
        - name: appconnect
          namespace: cp4i2
        - name: mq
          namespace: cp4i2
        - name: eventstreams
          namespace: cp4i2
        - name: eventendpointmgmt
          namespace: cp4i2
        - name: eventprocessing
          namespace: cp4i2
        - name: flink
          namespace: cp4i2
        - name: openshift-logging
          namespace: openshift-logging
        - name: openshift-telemetry
          namespace: openshift-tempo-operator
        - name: openshift-pipelines
          namespace: openshift-operators
        - name: cert-utils
          namespace: cert-utils-operator       
        - name: instana-agent
          namespace: openshift-operators
        - name: clusterresourceoverride
          namespace: cp4i2
        - name: assetrepository
          namespace: cp4i2
  template:
    metadata:
      name: '{{name}}-operator'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      project: cp4i-operators
      source:
        path: 'components/{{name}}/operator'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
