kind: Secret
apiVersion: v1
metadata:
  name: tempostack-s3
  namespace: openshift-tempo-operator
data:
  access_key_id: V2RVQ0h5UGNsT1Z1ZlhuZ0lwU0I=
  access_key_secret: enVqcWhPYUJLYSs2VjM1NzVaSFJSRlJEdnh6ZnVwdGZzVUp0a1liYg==
  bucket: dGVtcG8tYnVja2V0LTRmNDY5MDk1LWJiMzEtNGM3OS05ZTM0LWI1OTg3MWNiZTVlNQ==
  endpoint: aHR0cHM6Ly9zMy5vcGVuc2hpZnQtc3RvcmFnZS5zdmM=
type: Opaque


oc create secret generic tempostack-ibmcos \
  --from-literal=bucket="roks-tempo-navpoc" \
  --from-literal=endpoint="s3.private.eu-de.cloud-object-storage.appdomain.cloud" \
  --from-literal=access_key_id="8526434dae0440f28514d9087d8d0165" \
  --from-literal=access_key_secret="8224b33e0f47d4634d31d86547ea512e2303fb5f3e9bd4cb"